/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    _Icon: typeof import('./src/components/_shared/icons/_Icon.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Collapse: typeof import('./src/components/Collapse/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/Collapse/CollapseItem.vue')['default']
    ExpandTransition: typeof import('./src/components/_shared/components/ExpandTransition.vue')['default']
    FloatingPopup: typeof import('./src/components/FloatingPopup/index.vue')['default']
    IconClose: typeof import('./src/components/_shared/icons/IconClose.vue')['default']
    IconLoading: typeof import('./src/components/_shared/icons/IconLoading.vue')['default']
    Mask: typeof import('./src/components/Mask/index.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    ModalService: typeof import('./src/components/Modal/ModalService.vue')['default']
    Popup: typeof import('./src/components/Popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spin: typeof import('./src/components/Spin/index.vue')['default']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanFloatingPopup: typeof import('vant/es')['FloatingPopup']
  }
}
