/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    _Icon: typeof import('./src/components/_shared/icons/_Icon.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox/Checkbox.vue')['default']
    CheckboxGroup: typeof import('./src/components/Checkbox/CheckboxGroup.vue')['default']
    Collapse: typeof import('./src/components/Collapse/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/Collapse/CollapseItem.vue')['default']
    CxCheckbox: typeof import('./src/components/cx-checkbox/index.vue')['default']
    CxMessage: typeof import('./src/components/cx-message/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog/Dialog.vue')['default']
    DialogService: typeof import('./src/components/Dialog/DialogService.vue')['default']
    ExpandTransition: typeof import('./src/components/_shared/components/ExpandTransition.vue')['default']
    FloatingPopup: typeof import('./src/components/FloatingPopup/index.vue')['default']
    IconClose: typeof import('./src/components/PopupSwiper/component/IconClose.vue')['default']
    IconLoading: typeof import('./src/components/_shared/icons/IconLoading.vue')['default']
    IconLoadingArc: typeof import('./src/components/Loading/component/IconLoadingArc.vue')['default']
    IconLoadingCircle: typeof import('./src/components/Loading/component/IconLoadingCircle.vue')['default']
    IconLoadingSpin: typeof import('./src/components/Loading/component/IconLoadingSpin.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    Mask: typeof import('./src/components/Mask/index.vue')['default']
    Message: typeof import('./src/components/Message/index.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    ModalService: typeof import('./src/components/Modal/ModalService.vue')['default']
    Overlay: typeof import('./src/components/Overlay/index.vue')['default']
    Popover: typeof import('./src/components/Popover/index.vue')['default']
    Popup: typeof import('./src/components/Popup/index.vue')['default']
    PopupSwiper: typeof import('./src/components/PopupSwiper/index.vue')['default']
    Radio: typeof import('./src/components/Radio/Radio.vue')['default']
    RadioGroup: typeof import('./src/components/Radio/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spin: typeof import('./src/components/Spin/index.vue')['default']
    Sticky: typeof import('./src/components/Sticky/index.vue')['default']
    Switch: typeof import('./src/components/Switch/index.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip/index.vue')['default']
    Trigger: typeof import('./src/components/Trigger/index.vue')['default']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanFloatingPopup: typeof import('vant/es')['FloatingPopup']
  }
}
