/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    _Icon: typeof import('./src/components/_shared/icons/_Icon.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    ButtonGroup: typeof import('./src/components/Button/ButtonGroup.vue')['default']
    Collapse: typeof import('./src/components/Collapse/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/Collapse/CollapseItem.vue')['default']
    Drawer: typeof import('./src/components/Drawer/Drawer.vue')['default']
    DrawerService: typeof import('./src/components/Drawer/DrawerService.vue')['default']
    ExpandTransition: typeof import('./src/components/_shared/components/ExpandTransition.vue')['default']
    Mask: typeof import('./src/components/Mask/index.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    ModalService: typeof import('./src/components/Modal/ModalService.vue')['default']
    Popup: typeof import('./src/components/Popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanDialog: typeof import('vant/es')['Dialog']
    VantDialog: typeof import('vant/es')['tDialog']
  }
}
